---
fixes:
  - |
    Rbd replication secondary device could set different user and keyring with primary cluster.
    Secondary secret_uuid value is configed in libvirt secret, and libvirtd using secondary secret
    reconnect to secondary cluster after Cinder failover host.
