---
features:
  - |
    [`blueprint application-credentials <https://blueprints.launchpad.net/keystone/+spec/application-credentials>`_]
    Support for authentication via an application credential has been added.
    Keystoneauth can now be used to authenticate to Identity servers that
    support application credentials.
